#!/usr/bin/python

import os, sys, subprocess

cmd = "drbdadm role data|awk -F'/' '{print $1}'"
run_it = os.popen(cmd).readline().strip()
try:
	if run_it == "Primary":
		subprocess.call('drbdadm disconnect data', shell=True)
		subprocess.call('drbdadm connect data', shell=True)
        sys.exit(0)
   elif run_it == "Secondary":
		print "This node is marked as Secondary, please run it on the Primary node"
		sys.exit(1)
except ValueError:
	print "Someone GOOFED somewhere. . . YOU SHOULD NEVER SEE THIS MESSAGE"
	sys.exit(1)

