#!/usr/bin/python

import os, sys, subprocess

# Execute on Secondary Node

cmd = "drbdadm role data|awk -F'/' '{print $1}'"
run_it = os.popen(cmd).readline().strip()

try:
	if run_it == "Secondary":
		subprocess.call('drbdadm disconnect data', shell=True)
		subprocess.call('drbdadm secondary data', shell=True)
		subprocess.call('drbdadm connect --discard-my-data data', shell=True)
		sys.exit(0)
	else:
		print "This is not the Secondary Node"
		sys.exit(1) 
except ValueError:
	print "Someone GOOFED somewhere. . . YOU SHOULD NEVER SEE THIS MESSAGE"
	sys.exit(2)
